git:
  diffContextSize: 9999
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side

gui:
  authorColors:
    '*': '#b4befe'

  expandedSidePanelWeight: 100
  expandFocusedSidePanel: true
  scrollHeight: 15
  showCommandLog: false
  sidePanelWidth: 0.2

  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

keybinding:
  universal:
    prevBlock-alt: ""
    nextBlock-alt: ""
    jumpToBlock:
      - "1"
      - "h"
      - "3"
      - "4"
      - "5"
    focusMainView: "l"
